Bail out when decompression failed

diff --git a/myvim b/myvim
--- a/myvim
+++ b/myvim
@@ -85,7 +85,7 @@ BASE=$MYVIM/'$MD5'
 if [ ! -d $BASE/.vim ]; then
   >&2 echo "Extracting Vim environment to $BASE"
   mkdir -p $BASE
-  sed "1,/^# EOF #$/d" "$0" | tar -C $BASE -x '$COMPRESS'
+  sed "1,/^# EOF #$/d" "$0" | tar -C $BASE -x '$COMPRESS' || (echo Failed; exit 1)
   (cd $BASE
    mv -f .vimrc .vimrc.org
    echo "let [s:home_org, \$HOME] = [\$HOME, \"$BASE\"]" > .vimrc
